# Generated by Django 5.0.7 on 2024-10-11 02:25

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                (
                    "blood",
                    models.CharField(
                        choices=[
                            ("B+", "B+"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("O", "O"),
                            ("O+", "O+"),
                            ("AB", "AB"),
                            ("AB+", "AB+"),
                        ],
                        max_length=10,
                    ),
                ),
                ("lastDonatedDate", models.DateField(null=True)),
                ("photo", models.ImageField(blank=True, default=None, upload_to="")),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="number",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
