# Generated by Django 5.0.7 on 2024-10-13 14:57

import autoslug.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_doners_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doners",
            name="lastDonatedDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="doners",
            name="photo",
            field=models.ImageField(blank=True, default="patient.webp", upload_to=""),
        ),
        migrations.AlterField(
            model_name="doners",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="phone",
                unique=True,
            ),
        ),
    ]
