# Generated by Django 5.0.7 on 2024-10-10 04:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0004_emergencies_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencies",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
