# Generated by Django 5.0.7 on 2024-10-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0005_emergencies_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencies",
            name="photo",
            field=models.ImageField(
                blank=True, default="patient.webp", upload_to="media"
            ),
        ),
    ]
