# Generated by Django 5.0.7 on 2024-10-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0006_alter_emergencies_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencies",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="emergencies",
            name="photo",
            field=models.ImageField(blank=True, default="patient.webp", upload_to=""),
        ),
    ]
