# Generated by Django 5.0.7 on 2024-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0008_alter_emergencies_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencies",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
