# Generated by Django 5.0.7 on 2024-10-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0010_emergencies_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencies",
            name="author",
        ),
    ]
