# Generated by Django 5.0.7 on 2024-10-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0012_emergencies_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencies",
            name="slug",
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
